# File managed by pluginsync
sudo: required
language: cpp
services:
  - docker
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
before_install:
##- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
  - docker pull ubuntu:yakkety
  - docker build -t for-worker-box -f scripts/Dockerfile.travis .
install:
  - docker run -dt --name "worker-box" -e TEST_TYPE -v ${TRAVIS_BUILD_DIR}/:/opt/${TRAVIS_REPO_SLUG}/ -v ${TRAVIS_BUILD_DIR}/scripts/:/opt/scripts/ for-worker-box bash
script:
  - docker exec -ti worker-box bash -c "cd /opt/${TRAVIS_REPO_SLUG} && ./autogen.sh && ./configure && make test"
after_script:
  - docker rm -fv worker-box
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=

